name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake svg
    steps:
      - uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: Th4llesSo4res
          outputs: |
            ./output/github-contribution-grid-snake.svg
          # PersonalizaÃ§Ãµes ğŸ‘‡
          color_snake: neon
          color_dots: "#444444, #666666, #888888, #AAAAAA, #CCCCCC"
          grid_size: 10
          background: "#000000"

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "ğŸ update snake animation"
          add: "output/github-contribution-grid-snake.svg"
